site_name: Codecheck Documentation

# Good themes: readthedocs, yeti, journal
# Not elegantly responsive: readable, cosmo, flatly, spacelab, cerulean, slate, mkdocs, journal
# Color does not match codecheck: cyborg, united, amelia, mkdocs
# Font does not match codecheck: simplex
# Bleh in general: bootstrap
theme: readthedocs

use_directory_urls: true
docs_dir: source
site_dir: docs

pages:
## English pages:
- "": index.md            # DO NOT change this path. Build.py will fail.
- Welcome:                en/index.md # DO NOT change this path. Build.py will fail.
- Organizing Challenges: en/guide_organizing_challenges.md
- Reference:              en/reference_users.md
- Organizer Reference:   en/reference_organizers.md
##
## Japanese Pages:
- はじめに:                ja/index.md # DO NOT change this path. Build.py will fail.
- チャレンジの運営:       ja/guide_organizing_challenges.md
- よくある質問:            ja/Q-and-A.md
- リファレンス:            ja/reference_users.md
- 運営者リファレンス:      ja/reference_organizers.md
